name: Run tests

on:
  pull_request:
    - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - terraform init

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - terraform validate

jobs:
  tests:
    runs-on: ubuntu-latest

    steps: terraform plan

